### ISSUE TITLE
acme error on docker-kong

### ISSUE THREAD

**Issue by lukasa1993** [Kong/kong-plugin-acme#39]
hello i am running kong from official docker `:latest` and `:2.1` trying to set acme plugin i have dummy service and route and when i am trying to invoke domain with `curl -k` i get this :

```
 handler.lua:104 failed to update certificate: acme directory request failed: 18: self signed certificate
```

db is `postgres:9` have this `KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/ssl/certs/ca-certificates.crt` in env

it seems that it doesn't like `/etc/ssl/certs/ca-certificates.crt` i checked file is there…

**Comment by lukasa1993** [comment]
https://github.com/fffonion/lua-resty-acme/blob/f4f2027437348487a2108b6f525f2e84d0c9b1e1/lib/resty/acme/client.lua#L110

fails here… seems like it gets `18: self signed certificate` on acme url… i use default one `https://acme-v02.api.letsencrypt.org/directory`

@fffonion any idea ?

**Comment by fffonion** [comment]
Hi @lukasa1993, can you share the full kong.conf or any other environment variables you are passing to the container?

**Comment by lukasa1993** [comment]
@fffonion 
```
kong:
    image: kong:2.1
    container_name: kong
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/ssl/certs/ca-certificates.crt
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: 1
      KONG_PG_DATABASE: 2
      KONG_PG_HOST: 3
      KONG_PG_USER: 4
      KONG_PG_PASSWORD: 5
    networks:
      - kong
    ports:
      - "80:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
```

this is all i don't have custom kong.conf

i tried :latest as well same error
